language: node_js
node_js:
- 12
deploy:
  provider: heroku
  api_key:
    secure: eX2yaYuVr9+jrvd+1PTDBVe3xHAr1TvAn2P+/cOuCveUEGRB0Go6EL1ZMjq53+UUMKBAo2aA0N5At/a4j4HjU4psFMaPZKZO8UekrvSMN6lfTeRnPiZpmBFv11fuhwuvHX8W753sfcbrNdevc1vCgFU16TOrZVBZEpClIJqtEhbDYXFCzB4qwIsoDpiQVo+BhV0DIKcRcsPkeNo2piaTDGngrwtC/ZfC0PqoA2TDgsTLWK3v3GId16zq4+AMt4CwNPEC8OJ7WBKira9O9Oj3OOalkymnXp1rDWIj3Mn15/D7A/3TvFT4uD9Lmvfw0jm6bcgjD50M64LRTlVm9pVmESfE1hBZZ/Mt2v0xhYmBS/+4/jjF2QpdtR5itfiSxDIa7NaFlX/e7aHSLQxGKcRZgv7sYGqulNKp9VXYHpjLT3V0fcQdX5DYVJonOi38wsySUs8hU4rXGRlFV94w43RePihPBtLCk52sFR/Ftegl7oi6mASCKKqFyrWGfylBs5C6aE0dDsYN/dbK7TmN59VvKLUrY60RAqIfZg0gzUkyuEbf+BcThwiLrfyhAVRevh+6kWHXjA2GVAYwHIRJI4wZL2FnF/92wC2gCWNQJE4/hLn/ZeloyoFcUY+z/4t/lwupO5VZwOD86k7x2fkiUbOOtLaESg/xVvII9B7lai2XWiA=
  on: main